version: '3'

services:
  nginx:
    container_name: nginx
    image: ENTER_THE_DOCKER_USER_NAME/laravel-deploy-with-docker-nginx:latest
    ports:
      - "80:8080"

  php:
    container_name: php
    image: ENTER_THE_DOCKER_USER_NAME/laravel-deploy-with-docker-php:latest


